[theme]
base = "light"
primaryColor = "#005C56"
backgroundColor = "#FAFBFC"
secondaryBackgroundColor = "#F1F3F6"
textColor = "#11151A"
linkColor = "#236997"
borderColor = "#D5DAE1"
chartCategoricalColors = ["#009786", "#8670c0", "#ba673f", "#2b88c0", "#b4608a", "#a28218"]
font = "IBM Plex Sans:https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400&display=swap, sans-serif"
headingFont = "Space Grotesk:https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400..700&display=swap, sans-serif"
codeFont = "IBM Plex Mono:https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap, monospace"
headingFontSizes = ["2rem", "1.5rem", "1.125rem"]
headingFontWeights = 600
baseRadius = "0.5rem"

[theme.sidebar]
backgroundColor = "#F1F3F6"
secondaryBackgroundColor = "#FAFBFC"
borderColor = "#E3E7EC"

[server]
headless = true

[client]
toolbarMode = "minimal"
